# In this file, you can configure which tools to include in your tests.
# For each tool, you can provide a specific commit (or tag) to be used in your test.
# By default, we include all the tools, with the respective versions employed in our experiment.
# You can indicate a different commit/tag, or completely exclude a tool by commenting the respective lines.

# # GraphAligner
GraphAligner:
  version: b9a6fdc

# # VG Toolkit
#vg:
#  version: a7b0f38

# # AStarix
#astarix:
#  version: 23232ee

# # GWFA
#gwfa:
#  version: 0dd07ff

# # SGA
#SGA:
#  version: 577a3be

# # GEDMAP
#gedmap:
#  version: dc65d53

# V-ALIGN
#V-ALIGN:
#   version: e4b59a4

